### ISSUE TITLE
Command description in help is null

### ISSUE THREAD

**Issue by Blovien** [Electroid/intake#11]
![null](https://user-images.githubusercontent.com/20379165/49108471-93909400-f288-11e8-9ea0-3848b76d2b1a.png)

__How can I fix that?__
- Using the bukkit folder in the repository.
- Using Spigot 1.8.8

___Set command___
![generation](https://user-images.githubusercontent.com/20379165/49108599-e1a59780-f288-11e8-9b7c-e08d5ee89654.png)

___Wand command___
![wand](https://user-images.githubusercontent.com/20379165/49109086-1e25c300-f28a-11e8-8a77-7ec2ba5a9249.png)

___onLoad method___
![onload](https://user-images.githubusercontent.com/20379165/49108752-44972e80-f289-11e8-890f-03d015580bf1.png)

***Thanks in advice***

**Comment by Electroid** [comment]
Thanks for the issue request @Blovien, I'll look into this right away!

**Comment by Blovien** [comment]
Thanks for the reply. I'll wait!

**Comment by Electroid** [comment]
This bug has been annoying for years, literally! But it's fixed now 59f112a279b44d1ee28a2f7361a10f75e4d0d6af

**Comment by Blovien** [comment]
Thank you!
