### ISSUE TITLE
Google error

### ISSUE THREAD

**Issue by Loapu** [Electroid/intake#15]
When I use intake v1.1-SNAPSHOT the following error shows inside the console

`07.05 22:45:53 [Server] INFO java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
07.05 22:45:53 [Server] INFO at dev.loapu.vestriafoodproject.libs.intake.parametric.ParametricBuilder.<init>(ParametricBuilder.java:51) ~[?:?]
07.05 22:45:53 [Server] INFO at dev.loapu.vestriafoodproject.libs.intake.bukkit.graph.BasicBukkitCommandGraph.<init>(BasicBukkitCommandGraph.java:21) ~[?:?]
07.05 22:45:53 [Server] INFO at dev.loapu.vestriafoodproject.VestriaFoodProject.registerCommands(VestriaFoodProject.java:88) ~[?:?]
07.05 22:45:53 [Server] INFO at dev.loapu.vestriafoodproject.VestriaFoodProject.onEnableInner(VestriaFoodProject.java:74) ~[?:?]`

I use Spigot (CraftBukkit version git-Spigot-f56e2e7-1a64d4a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)) on my server. Does this happen because I shadowed the library or is there anything you can do about it?

**Comment by zeshan321** [comment]
I had the same issue. I cloned and built: https://github.com/Electroid/intake/pull/12 and that fixes the dependency issues.

**Comment by Electroid** [comment]
I did note this in #17, will try to work out a solution!

**Comment by Electroid** [comment]
Should be fixed now 59f112a279b44d1ee28a2f7361a10f75e4d0d6af
